config/routes.rb
Rails.application.routes.draw do
  get 'overview', to: 'overview#home', as: 'overview'

  get 'revenue/commissions'

  resources :vehicles
  resources :clients
  resources :policies
  resources :insurers

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'overview#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  def home
    @clients = current_user.clients
    @policies = current_user.policies
    @vehicles = current_user.vehicles
    @insurers = current_user.insurers
  end
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/views/overview/_client_table_summary.html.erb
<div class="ui top attached blue clearing segment">
  <h4 class="ui left blue floated header">
      <i class="users icon"></i>
      <div class="content">
        Clients
        <div class="sub header">
          Showing <b><%= clients.take(5).count %></b> of <b><%= pluralize(clients.count, 'client') %></b>
        </div>
      </div>
  </h4>
  <%= link_to new_client_path do %>
    <div class="ui blue circular basic icon large button right floated" data-tooltip="add new client" data-inverted="" data-position="bottom center">
      <i class="plus icon"></i>
    </div>
  <% end %>
</div>

<div class="ui bottom attached segment">
  <table class="ui unstackable selectable teal fixed single line very basic small table">
    <thead>
      <tr>
        <th>Lastname</th>
        <th>Other names</th>
        <th class="right aligned">Telephone</th>
      </tr>
    </thead>
    <tbody>
      <% if clients.any? %>
        <% clients.take(5).each do |client| %>
          <tr>
            <td class="selectable"><%= link_to client.lastname, client %></td>
            <td class="selectable"><%= link_to(client.other_names, client) || '-' %></td>
            <td class="selectable right aligned"><%= link_to(client.telephone, client) || '-' %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="3" class="center aligned">you currently don't have any client info, <%= link_to 'add a new client', new_client_path %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot class="full-width">
      <tr>
        <th colspan="3">
          <h4 class="ui right floated header">
            <%= link_to 'all clients...', clients_path %>
          </h4>
        </th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/overview/_policy_table_summary.html.erb
<div class="ui top attached violet clearing segment">
  <h4 class="ui left violet floated header">
      <i class="folder open icon"></i>
      <div class="content">
        Policies
        <div class="sub header">
          Showing <b><%= policies.take(5).count %></b> of <b><%= pluralize(policies.count, 'policy') %></b>
        </div>
      </div>
  </h4>
  <%= link_to new_policy_path do %>
    <div class="ui violet circular basic icon large button right floated" data-tooltip="add new policy" data-inverted="" data-position="bottom center">
      <i class="plus icon"></i>
    </div>
  <% end %>
</div>

<div class="ui bottom attached segment">
  <table class="ui unstackable selectable teal fixed single line very basic small table">
    <thead>
      <tr>
        <th>Policy No.</th>
        <th>Asset</th>
        <th>Insurer</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% if policies.any? %>
        <% policies.take(5).each do |policy| %>
          <tr>
            <td data-tooltip="<%= policy_cell_pop_up policy %>" data-position="right center">
              <%= policy.number ? (link_to policy.number, policy) : (link_to "Policy number not given", policy) %>
            </td>
            <td>
              <!--IDEA icon dependant on asset type, will have to remove cell's selectable class though -->
              <%= link_to "#{policy.vehicle ? policy.vehicle.registration_no : "--"}", '#' %>
            </td>
            <td><%= policy.insurer ? link_to(policy.insurer.name.upcase, policy.insurer) : '--unavailable--' %></td>
            <td class="<%= policy_table_cell_class policy %>" data-tooltip="<%= policy_cell_pop_up policy %>" data-position="left center">
              <%= policy.status.humanize + " #{'(expired)' if policy.expired?}" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4" class="center aligned">you currently don't have any policy info, <%= link_to 'add a new policy', new_policy_path %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot class="full-width">
      <tr>
        <th colspan="4">
          <h4 class="ui right floated header">
            <%= link_to 'all policies...', policies_path %>
          </h4>
        </th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/overview/_vehicle_table_summary.html.erb
<div class="ui top attached purple clearing segment">
  <h4 class="ui left purple floated header">
      <i class="car icon"></i>
      <div class="content">
        Vehicles
        <div class="sub header">
          Showing <b><%= vehicles.take(5).count %></b> of <b><%= pluralize(vehicles.count, 'vehicle') %></b>
        </div>
      </div>
  </h4>
  <%= link_to new_vehicle_path do %>
    <div class="ui purple circular basic icon large button right floated" data-tooltip="add new vehicle" data-inverted="" data-position="bottom center">
      <i class="plus icon"></i>
    </div>
  <% end %>
</div>

<div class="ui bottom attached segment">
  <table class="ui unstackable selectable teal fixed single line very basic small table">
    <thead>
      <tr>
        <th>Reg No</th>
        <th>Make</th>
        <th>Model</th>
        <th class="right aligned">Client</th>
      </tr>
    </thead>
    <tbody>
      <% if vehicles.any? %>
        <% @vehicles.take(5).each do |vehicle| %>
          <tr>
            <td><%= link_to vehicle.registration_no, vehicle %></td>
            <td><%= vehicle.make %></td>
            <td><%= vehicle.model %></td>
            <td class="right aligned"><%= link_to(("#{vehicle.client.lastname}#{vehicle.client.other_names ? ", #{vehicle.client.other_names}" : ""}"), vehicle.client) %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4" class="center aligned">you currently don't have any vehicle info, <%= link_to 'add a new vehicle', new_vehicle_path %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot class="full-width">
      <tr>
        <th colspan="4">
          <h4 class="ui right floated header">
            <%= link_to 'all vehicles...', vehicles_path %>
          </h4>
        </th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/overview/home.html.erb
<div class="ui container">
  <% if !@insurers.any? %>
    <div class="ui inverted yellow segment">
      <h2 class="ui header">
        <i class="warning icon"></i>
        <div class="content">
          You need to have at least 1 insurer in the system
          <div class="sub header">
            <%= link_to 'Click here to add a new insurer', new_insurer_path %>
          </div>
        </div>
      </h2>
    </div>
    <div class="ui divider"></div>
  <% end %>
  <%= render 'revenue/total_revenue_summary' %>
  <div class="ui hidden divider"></div>
  <div class="ui two column stackable grid">
    <div class="column">
      <h3 class="ui horizontal divider header">
        <i class="address book outline icon"></i>
        Clients & Policies
      </h3>
      <%= render 'policy_table_summary', policies: @policies %>
      <div class="ui hidden divider"></div>
      <%= render 'client_table_summary', clients: @clients %>
    </div>
    <div class="column">
      <h3 class="ui horizontal divider header">
        <i class="home icon"></i>
        Assets
      </h3>
      <%= render 'vehicle_table_summary', vehicles: @vehicles %>
      <div class="ui hidden divider"></div>
      <p>placeholder for houses and other assets</p>
    </div>
  </div>
</div>