config/routes.rb
Rails.application.routes.draw do
  get 'overview', to: 'overview#home', as: 'overview'

  get 'revenue/commissions'

  resources :vehicles
  resources :clients
  resources :policies
  resources :insurers

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'overview#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :vehicles
  has_many :policies, inverse_of: :client

  validates_presence_of :lastname
  validates_presence_of :user
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, allow_blank: true }

  # return client name in full name format
  def lastname_other_names
    "#{lastname} #{other_names || ""}"
  end

  def other_names_lastname
    "#{other_names+" " || ""} #{lastname}"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = current_user.clients
  end

  def show
  end

  def new
    @client = current_user.clients.new
  end

  def create
    @client = current_user.clients.new(client_params)
    if @client.save
      flash[:success] = "New client, #{@client.lastname} added!"
      redirect_to @client
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @client.update_attributes client_params
      flash[:success] = "Client info updated!"
      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    lastname = @client.lastname
    other_names = @client.other_names.blank? ? '' : "#{@client.other_names} "
    @client.destroy
    flash[:success] = "Client, #{other_names + lastname}, successfully removed!"
    redirect_to clients_url
  end

  private

    def set_client
      @client = Client.find(params[:id])
      check_user_authorization_for @client
    end

    def client_params
      params.require(:client).permit(:lastname, :other_names, :telephone, :email, :address)
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div class="ui centered raised teal card">
  <div class="content">
    <%= link_to edit_client_path @client do%>
      <div class="ui teal circular basic icon button right floated" data-tooltip="Edit client info" data-inverted="">
        <i class="write icon"></i>
      </div>
    <% end %>
    <div class="header">
      <%= @client.other_names || "" %> <%= @client.lastname %>
    </div>
    <div class="meta">
      <span>last edited <%= time_ago_in_words @client.updated_at %> ago</span>
    </div>
  </div>

  <div class="content">
    <div class="ui list">
      <div class="item">
        <i class="home icon"></i>
        <div class="content">
          <%= @client.address %>
        </div>
      </div>
      <div class="item">
        <i class="mail icon"></i>
        <div class="content">
          <%= @client.email %>
        </div>
      </div>
      <div class="item">
        <i class="call icon"></i>
        <div class="content">
          <%= @client.telephone %>
        </div>
      </div>
    </div>
  </div>

  <div class="extra content">
    <span class="right floated">
      Created <%= time_ago_in_words(@client.created_at, include_seconds: true) %> ago
    </span>
  </div>
</div>

app/views/clients/_client_form.html.erb
<!-- form -->
<%= form_for(client, html: { class: 'ui form' }) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <label>Name</label>
    <div class="two fields">

      <div class="field <%= "error" if client.errors.details.key? :lastname %>">
        <%= f.text_field :lastname, autofocus: true, placeholder: 'lastname' %>
        <%= render_error_label client, :lastname %>
      </div>

      <div class="field <%= "error" if client.errors.details.key? :other_names %>">
        <%= f.text_field :other_names, autofocus: true, placeholder: 'other names' %>
        <%= render_error_label client, :other_names %>
      </div>

    </div>
  </div>

  <div class="field <%= "error" if client.errors.details.key? :telephone %>">
    <%= f.label :telephone %>
    <div class="ui left icon input">
      <i class="call icon"></i>
      <%= f.telephone_field :telephone, autofocus: true, placeholder: 'phone #' %>
    </div>
    <%= render_error_label client, :telephone %>
  </div>

  <div class="field <%= "error" if client.errors.details.key? :email %>">
    <%= f.label :email %>
    <div class="ui left icon input">
      <i class="mail icon"></i>
      <%= f.email_field :email, autofocus: true, placeholder: 'email address' %>
    </div>
    <%= render_error_label client, :email %>
  </div>

  <div class="field <%= "error" if client.errors.details.key? :address %>">
    <%= f.label :address %>
    <%= f.text_area :address, autofocus: true, rows: 2 %>
    <%= render_error_label client, :address %>
  </div>

  <div class="actions">
    <div class="two ui buttons">
      <%= link_to 'Cancel', (request.referer.present? ? request.referer : authenticated_root_path), class:'ui button' %>
      <div class="or"></div>
      <%= f.submit action, class: "ui positive button" %>
    </div>
  </div>

<% end %>

app/views/clients/_client_table.html.erb
<table class="ui unstackable selectable teal table">
  <thead>
    <tr>
      <th>Lastname</th>
      <th>Other names</th>
      <th class="right aligned">Telephone</th>
    </tr>
  </thead>

  <% @clients.each do |client| %>
    <tr>
      <td class="selectable"><%= link_to client.lastname, client %></td>
      <td class="selectable"><%= link_to(client.other_names, client) || '-' %></td>
      <td class="selectable right aligned"><%= link_to(client.telephone, client) || '-' %></td>
    </tr>
  <% end %>
</table>

app/views/clients/_no_clients.html.erb
<div class="ui center aligned container">
    <%= image_tag("thinking-clipart.svg", class: "ui centered medium image") %>
    <div class="ui small header">
      looks like you don't have any client data yet, <%= link_to 'add a new client', new_client_path %>
    </div>
</div>

app/views/clients/edit.html.erb
<div class="ui grid container">

  <div class="row">
    <div class="sixteen wide mobile eight wide tablet eight wide computer column">

      <div class="ui header">
        <i class="write icon"></i>
        <div class="content">
          Edit Client
          <div class="sub header">
            Edit client information
          </div>
        </div>
      </div>

      <%= render 'client_form', client: @client, action:'Save changes' %>

      <div class="ui divider"></div>

      <div class="ui inverted clearing segment">
        <h5 class="ui red inverted header">
          Delete client
          <div class="sub header">
            This action permanently removes this client from the database.
            You will lose all related client data
          </div>
        </h5>
        <%= link_to @client, method: :delete, data: {confirm: "Are you sure you want to delete this client?"}, class:'ui inverted right floated red basic button' do %>
          <i class="icon trash"></i>
          Delete this client
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/clients/index.html.erb
<div class="ui container">
  <!-- page header -->
  <h1 class="ui left floated header">
    <i class="users icon"></i>
    <div class="content">
      Clients
      <div class="sub header">
        View all your clients
      </div>
    </div>
  </h1>

  <%= link_to new_client_path do %>
    <div class="ui teal circular basic icon large button right floated" data-tooltip="add new client" data-inverted="" data-position="bottom center">
      <i class="plus icon"></i>
    </div>
  <% end %>

  <!-- client list -->
  <%= render(@clients.any? ? 'client_table' : 'no_clients') %>
</div>

app/views/clients/new.html.erb
<div class="ui grid container">

  <div class="row">
    <div class="sixteen wide mobile eight wide tablet eight wide computer column">

      <div class="ui header">
        <i class="add user icon"></i>
        <div class="content">
          Add Client
          <div class="sub header">
            Add a new client to your portfolio
          </div>
        </div>
      </div>

      <%= render 'client_form', client:@client, action:'Add Client' %>

    </div>
  </div>

</div>

app/views/clients/show.html.erb
<div class="ui internally celled stackable grid container">
  <div class="row">
    <div class="five wide column">

      <!-- begin client card -->
      <%= render @client %>
      <!-- end client card -->

      <!-- go back to client list -->
      <%= link_to clients_path, class:'ui animated fade fluid teal basic button' do %>
        <div class="visible content">
          <i class="users icon"></i>
          clients
        </div>
        <div class="hidden content">
          go to Client list
        </div>
      <% end %>

    </div>

    <div class="eleven wide column">

      <!-- begin tabbed content -->

        <!-- menu options TODO make this sticky -->
        <div class="ui teal pointing secondary menu">
          <a class="item active" data-tab="policies"><i class="file text icon"></i>Policies</a>
          <a class="item" data-tab="vehicles"><i class="car icon"></i>Vehicles</a>
          <a class="item" data-tab="claims"><i class="first aid icon"></i>Claims</a>
        </div>

        <!-- 1. policies tab -->
        <div class="ui tab basic segment active" data-tab="policies">
          <% if @client.policies.empty? %>
            Client does not currently have any policies on their account. Add a new policy
          <% else %>
            <%= render partial: 'policies/policy_table', locals: { policies: @client.policies } %>
          <% end %>
        </div>

        <!-- 2. vehicles tab TODO change this to assets-->
        <div class="ui tab basic segment" data-tab="vehicles">
          <% if @client.vehicles.empty? %>
            <div class="ui center aligned teal segment">
              This client has no vehicles, add new vehicle <%= link_to 'here', new_vehicle_path %>
            </div>
          <% else %>
            <div class="ui cards">
              <%= render @client.vehicles %>
            </div>
          <% end %>
        </div>

        <!-- 3. claims -->
        <div class="ui tab basic segment" data-tab="claims">
          Client does not currently have any claims on their account
        </div>
      <!-- end tabbed content -->

    </div>
  </div>
</div>