config/routes.rb
Rails.application.routes.draw do
  get 'overview', to: 'overview#home', as: 'overview'

  get 'revenue/commissions'

  resources :vehicles
  resources :clients
  resources :policies
  resources :insurers

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'overview#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :client
  has_many :policies

  # TODO validate attributes
  # TODO validate uniqueness of chassis_no or registration_no??
  validates :year_of_manufacture, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :seating_capacity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :cubic_capacity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :registration_no, presence: true, format: { with: /\A[a-zA-Z\d]+\z/, message: 'only allows letters and numbers, please enter input without spaces' }
  # TODO further validate format of chassis_no
  validates :chassis_no, presence: true, length: { is: 17, wrong_length: "should be 17 characters in length" }, format: { with: /\A[a-zA-Z\d]+\z/, message: 'only allows letters and numbers, please enter input without spaces' }
  validates :make, presence: true
  validates :model, presence: true

  # TODO standardize input case before save
  # before_save do
    # make.capitalize!
    # model.capitalize!
    # registration_no.upcase!
    # chassis_no.upcase!
    # body_type.upcase!
  # end

  # TODO standardize input case before validations run
  before_validation do
    make.capitalize!
    model.capitalize!
    registration_no.upcase!
    chassis_no.upcase!
    body_type.upcase!
  end

  # return (registration number) make model string
  def reg_make_model
    "#{registration_no} (#{make} #{model})"
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  def index
    # should this be vehicles specific to current user or the whole system?
    # something like current_user.vehicles or current_user.clients.vehicles
    @vehicles = current_user.vehicles
  end

  def show
  end

  def new
    @vehicle = current_user.vehicles.new
  end

  def create
    @vehicle = current_user.vehicles.new(vehicle_params)
    if @vehicle.save
      flash[:success] = "#{@vehicle.client.other_names_lastname} has a new vehicle!"
      redirect_to @vehicle
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @vehicle.update_attributes vehicle_params
      flash[:success] = "Vehicle info updated!"
      redirect_to @vehicle
    else
      render 'edit'
    end
  end

  def destroy
    client = @vehicle.client
    vehicle_name = "#{@vehicle.year_of_manufacture} #{@vehicle.make} #{@vehicle.model}"
    @vehicle.destroy
    flash[:success] = "#{client.other_names_lastname}'s #{vehicle_name} deleted!"
    redirect_to client
  end

  private

    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
      check_user_authorization_for @vehicle
    end

    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year_of_manufacture, :body_type, :seating_capacity, :cubic_capacity, :registration_no, :chassis_no, :client_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_no_vehicles.html.erb
<div class="ui center aligned container">
  <%= image_tag("thinking-clipart.svg", class: "ui centered medium image") %>
  <div class="ui small header">
    looks like you don't have any vehicle data yet, <%= link_to 'add a new vehicle', new_vehicle_path %>
  </div>
</div>

app/views/vehicles/_vehicle.html.erb
<div class="ui centered raised teal card">
  <div class="content">
    <%= link_to edit_vehicle_path vehicle do%>
      <div class="ui teal circular basic icon button right floated" data-tooltip="Edit vehicle info" data-inverted="">
        <i class="settings icon"></i>
      </div>
    <% end %>
    <!-- Add header containing some vehicle related data. Current policy status for example -->
    <div class="meta">
      owned by <%= link_to(("#{vehicle.client.other_names || ""} #{vehicle.client.lastname}"), vehicle.client) %>
    </div>
  </div>
  <div class="image">
    <%= image_tag("placeholder.png") %>
  </div>
  <div class="content">
    <div class="header"><%= link_to "#{vehicle.year_of_manufacture} #{vehicle.make} #{vehicle.model}", vehicle  %></div>
    <div class="meta">
      <%= link_to vehicle.registration_no, vehicle %>
    </div>
    <div class="description">
      <!-- this should have policy expiration date, 'expires' if future, 'expired'
        if past. green if more than a month away, warning if within a month, red if expired -->
      Policy expires on: <h4 class="ui green header">February 28th 2018</h4>
    </div>
    <div class="ui list">
      <div class="item">
        <div class="ui label">
          Chassis No.
          <div class="detail"><%= vehicle.chassis_no %></div>
        </div>
      </div>
      <div class="item">
        <div class="ui label">
          Cubic Capacity
          <div class="detail"><%= vehicle.cubic_capacity %></div>
        </div>
      </div>
      <div class="item">
        <div class="ui label">
          Seating Capacity
          <div class="detail"><%= vehicle.seating_capacity %></div>
        </div>
      </div>
      <div class="item">
        <div class="ui label">
          Body Type
          <div class="detail"><%= vehicle.body_type %></div>
        </div>
      </div>
    </div>
  </div>
  <div class="extra content">
    <span class="right floated">
      Added <%= vehicle.created_at.to_formatted_s(:long) %>
    </span>
  </div>
</div>

app/views/vehicles/_vehicle_form.html.erb
<!-- form -->
<%= form_for(@vehicle, html: { class: 'ui form' }) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="three fields">
    <!-- change to dropdown -->
    <div class="field <%= "error" if @vehicle.errors.details.key? :make %>">
      <%= f.label :make %>
      <%= f.text_field :make, autofocus: true %>
      <%= render_error_label vehicle, :make %>
    </div>

    <!-- change to dropdown -->
    <div class="field <%= "error" if @vehicle.errors.details.key? :model %>">
      <%= f.label :model %>
      <%= f.text_field :model, autofocus: true %>
      <%= render_error_label vehicle, :model %>
    </div>

    <div class="field <%= "error" if @vehicle.errors.details.key? :year_of_manufacture %>">
      <%= f.label :year_of_manufacture, 'Year of Manufacture' %>
      <%= f.select :year_of_manufacture, (1950..(Time.now.year+1)).to_a.reverse, {prompt: "Select year"}, {class: "ui fluid selection dropdown"}%>
      <%= render_error_label vehicle, :year_of_manufacture %>
    </div>
  </div>

  <div class="three fields">
    <!-- change to dropdown -->
    <div class="field <%= "error" if @vehicle.errors.details.key? :body_type %>">
      <%= f.label :body_type, 'Body Type' %>
      <%= f.text_field :body_type, autofocus: true %>
      <%= render_error_label vehicle, :body_type %>
    </div>

    <div class="field <%= "error" if @vehicle.errors.details.key? :seating_capacity %>">
      <%= f.label :seating_capacity, 'Seating Capacity' %>
      <!-- <%= f.number_field :seating_capacity, autofocus: true %> -->
      <%= f.select :seating_capacity, (0..100).to_a, { prompt: "choose" }, { class: "ui fluid selection dropdown" } %>
      <%= render_error_label vehicle, :seating_capacity %>
    </div>

    <div class="field <%= "error" if @vehicle.errors.details.key? :cubic_capacity %>">
      <%= f.label :cubic_capacity, "Cubic Capacity (cc)" %>
      <%= f.number_field :cubic_capacity, autofocus: true %>
      <%= render_error_label vehicle, :cubic_capacity %>
    </div>
  </div>

  <div class="fields">
    <div class="six wide field">
      <div class="field <%= "error" if @vehicle.errors.details.key? :registration_no %>">
        <%= f.label :registration_no, 'Registration Number' %>
        <%= f.text_field :registration_no, autofocus: true %>
        <%= render_error_label vehicle, :registration_no %>
      </div>
    </div>

    <div class="ten wide field">
      <div class="field <%= "error" if @vehicle.errors.details.key? :chassis_no %>">
        <%= f.label :chassis_no, 'Chassis Number' %>
        <!-- length of chassis_no post 1981 is 17 characters -->
        <%= f.text_field :chassis_no, maxlength: 17, size: 17, autofocus: true %>
        <%= render_error_label vehicle, :chassis_no %>
      </div>
    </div>
  </div>

  <!-- change to dropdown -->
  <div class="field <%= "error" if @vehicle.errors.details.key? :client %>">
    <%= f.label :client %>
    <!-- <%= f.text_field :client, autofocus: true %> -->
    <%= f.collection_select :client_id, current_user.clients.all, :id, :lastname_other_names,{prompt: "Select the vehicle owner"}, {class: "ui search dropdown"} %>
    <%= render_error_label vehicle, :client %>
  </div>

  <div class="actions">
    <div class="two ui buttons">
      <%= link_to 'Cancel', (request.referer.present? ? request.referer : authenticated_root_path), class:'ui button' %>
      <div class="or"></div>
      <%= f.submit action, class: "ui positive button" %>
    </div>
  </div>
<% end %>

app/views/vehicles/_vehicle_table.html.erb
<table class="ui unstackable selectable teal table">
  <thead>
    <tr>
      <th>Reg No</th>
      <th>Make</th>
      <th>Model</th>
      <th class="right aligned">Client</th>
    </tr>
  </thead>

  <% @vehicles.each do |vehicle| %>
    <tr>
      <td class="selectable"><%= link_to vehicle.registration_no, vehicle %></td>
      <td><%= vehicle.make %></td>
      <td><%= vehicle.model %></td>
      <td class="selectable right aligned"><%= link_to(("#{vehicle.client.lastname}#{vehicle.client.other_names ? ", #{vehicle.client.other_names}" : ""}"), vehicle.client) %></td>
    </tr>
  <% end %>
</table>

app/views/vehicles/edit.html.erb
<div class="ui grid container">

  <div class="row">
    <div class="sixteen wide mobile eight wide tablet eight wide computer column">

      <div class="ui header">
        <i class="car icon"></i>
        <div class="content">
          Edit Vehicle
          <div class="sub header">
            Edit Vehicle information
          </div>
        </div>
      </div>

      <%= render 'vehicle_form', vehicle: @vehicle, action: 'Save changes' %>

      <div class="ui divider"></div>

      <div class="ui inverted clearing segment">
        <h5 class="ui red inverted header">
          Delete vehicle
          <div class="sub header">
            This action permanently removes this vehicle from the database.
            You will lose all related vehicle data
          </div>
        </h5>
        <%= link_to @vehicle, method: :delete, data: {confirm: "Are you sure you want to delete this vehicle?"}, class:'ui inverted right floated red basic button' do %>
          <i class="icon trash"></i>
          Delete this vehicle
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/vehicles/index.html.erb
<div class="ui container">
  <!-- page header -->
  <h1 class="ui left floated header">
    <i class="car icon"></i>
    <div class="content">
      Vehicles
      <div class="sub header">
        View all vehicles
      </div>
    </div>
  </h1>

  <%= link_to new_vehicle_path do %>
    <div class="ui teal circular basic icon large button right floated" data-tooltip="add new vehicle" data-inverted="" data-position="bottom center">
      <i class="plus icon"></i>
    </div>
  <% end %>

  <!-- vehicle list -->
  <%= render(@vehicles.any? ? 'vehicle_table' : 'no_vehicles') %>
</div>

app/views/vehicles/new.html.erb
<div class="ui grid container">

  <div class="row">
    <div class="sixteen wide mobile eight wide tablet eight wide computer column">

      <div class="ui header">
        <i class="car icon"></i>
        <div class="content">
          Add Vehicle
          <div class="sub header">
            Add a new vehicle to your portfolio
          </div>
        </div>
      </div>

      <%= render 'vehicle_form', vehicle: @vehicle, action: 'Add Vehicle' %>

    </div>
  </div>

</div>

app/views/vehicles/show.html.erb
<div class="ui internally celled stackable grid container">
  <div class="row">
    <div class="five wide column">
      <!-- vehicle card -->
      <%= render @vehicle %>

      <!-- go back to vehicle list -->
      <%= link_to vehicles_path, class:'ui animated fade fluid teal basic button' do %>
        <div class="visible content">
          <i class="car icon"></i>
          vehicles
        </div>
        <div class="hidden content">
          go to Vehicle list
        </div>
      <% end %>
    </div>

    <div class="eleven wide column">

      <h2 class="ui left floated header">
        <div class="content">
          <%= @vehicle.registration_no %>
          <div class="sub header">
            <i>registration number</i>
          </div>
        </div>
      </h2>

      <div class="ui clearing divider"></div>

      <!-- make this vary color depending on policy status -->
      <div class="ui center aligned clearing segment">
        <h3 class="ui header">
          This vehicle is currently <%= @vehicle.policies.issued.empty? ? "not covered" : "covered under a policy expiring in ... days/months/years" %>
        </h3>
      </div>

      <!-- begin policies -->
      <table class="ui unstackable selectable teal table">
        <thead>
          <tr>
            <th colspan="3" class="center aligned"><%=@vehicle.registration_no%>'s policies</th>
          </tr>
          <tr>
            <th>Policy No.</th>
            <th>Insurer</th>
            <th>Status</th>
          </tr>
        </thead>

        <% if @vehicle.policies.any? %>
          <% @vehicle.policies.each do |policy| %>
            <tr>
              <td class="selectable"><%= policy.number ? (link_to policy.number, policy) : (link_to "Policy number not issued", policy) %></td>
              <td class="selectable"><%= policy.insurer ? link_to(policy.insurer.name.upcase, policy.insurer) : '--unavailable--' %></td>
              <td class="selectable"><%= link_to policy.status, policy %></td>
            </tr>
          <% end %>
        <% end %>
      </table>
      <!-- end policies -->

      <!-- begin claims -->
      <!-- end claims -->

      <!-- begin revenue -->
        <h3 class="ui horizontal divider header">
          <i class="dollar icon"></i>
          Commission Revenue
        </h3>
        <div class="ui stackable grid container">
          <div class="six wide column">
            <div class="ui horizontal statistics">
              <!-- amount made from currently valid (issued, non-expired) policies -->
              <div class="green statistic">
                <div class="value">
                  <% if @vehicle.policies.any? %>
                    <%= number_to_currency(@vehicle.policies.issued.sum(:commission_amount), unit:"GH₵") %>
                  <% else %>
                    --
                  <% end %>
                </div>
                <div class="label">
                  from current policies
                </div>
              </div>
              <!-- cumulative amount made from valid (issued, expired included) policies -->
              <div class="olive statistic">
                <div class="value">
                  <% if @vehicle.policies.any? %>
                    <!-- TODO introduce helper method to select policies that meet above criteria -->
                    <%= number_to_currency(@vehicle.policies.issued.sum(:commission_amount), unit:"GH₵") %>
                  <% else %>
                    --
                  <% end %>
                </div>
                <div class="label">
                  cumulative past & present
                </div>
              </div>
            </div>
          </div>
          <div class="one wide column">
            <!-- gutter -->
          </div>
          <div class="nine wide column">
            <% if @vehicle.policies.any? %>
              <!-- TODO modify this to display value on chart in currency format -->
              <%= line_chart @vehicle.policies.group_by_hour(:created_at).sum(:commission_amount), ytitle:"GH₵" %>
            <% else %>
              <%= line_chart [], ytitle:"GH₵" %>
            <% end %>
          </div>
        </div>
      <!-- end revenue -->
    </div>
  </div>
</div>