config/routes.rb
Rails.application.routes.draw do
  get 'overview', to: 'overview#home', as: 'overview'

  get 'revenue/commissions'

  resources :vehicles
  resources :clients
  resources :policies
  resources :insurers

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'overview#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/policy.rb
class Policy < ApplicationRecord
  include Sanitizable
  belongs_to :client
  belongs_to :vehicle, optional: true
  belongs_to :user
  belongs_to :insurer
  enum status: [ :not_issued, :issued, :cancelled ] # TODO add expired, valid

  before_validation :squish_inputs, :nil_if_blank, :calculate_commission_amount # remove whitespace, calculate commission amount

  validates_uniqueness_of :number, scope: [:insurer, :user], message: "must be unique to the given insurer"  # There HAS to be a more elegant way of doing this. Currently replaced has_many :through relationship between policy and user with has_many & belongs_to
  validates_presence_of :number, allow_nil: true # TODO validate number to disallow whitespace only input
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate  :end_date_after_start_date
  validates :premium, presence: true, numericality: { greater_than_or_equal_to: 0, message: "must be number 0 or greater" }
  validates :commission, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100, message: "must be a percentage between 0 and 100" }
  validates :discount, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100, message: "must be a percentage between 0 and 100" }
  validates :client, presence: true
  validates :insurer, presence: true
  validates :user, presence: true
  validates :commission_amount, numericality: { greater_than_or_equal_to: 0 }

  def expired?
    if end_date
      end_date.past?
    else
      false
    end
  end

  private

    def calculate_commission_amount
      # TODO apply discount to premium
      self.commission_amount = (self.premium * (self.commission/100)) if self.commission
    end

    def end_date_after_start_date
      if end_date && (end_date < start_date)
        errors.add :end_date, "has to be same as or after Start date"
      end
    end

end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  def index
    @policies = current_user.policies
  end

  def show
  end

  def new
    @policy = current_user.policies.new
  end

  def create
    @policy = current_user.policies.new(policy_params)
    if @policy.save
      flash[:warning] = "#{@policy.client.other_names_lastname} has a new policy! Please note that the policy is currently: #{@policy.status.humanize}"
      redirect_to @policy
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @policy.update_attributes policy_params
      flash[:success] = "Policy info updated!"
      redirect_to @policy
    else
      render 'edit'
    end
  end

  def destroy
    client = @policy.client
    @policy.destroy
    flash[:success] = "Policy belonging to #{client.other_names_lastname} deleted!"
    redirect_to client
  end

  private

    def set_policy
      @policy = Policy.find(params[:id])
      check_user_authorization_for @policy
    end

    def policy_params
      params.require(:policy).permit(:insurer_id, :number, :policy_type, :status, :issue_date, :start_date, :end_date, :premium, :commission, :discount, :client_id, :vehicle_id)
    end
end

app/helpers/policies_helper.rb
module PoliciesHelper
  # return cell class depending on policy status
  def policy_table_cell_class policy
    if policy.expired?
      'negative'
    elsif (policy.not_issued? || policy.cancelled?)
      'warning'
    else
      'positive'
    end
  end

  # return cell popup content depending on policy status
  def policy_cell_pop_up policy
    if policy.expired?
      "Expired: " + policy.end_date.to_s(:rfc822)
    elsif policy.not_issued?
      "Not issued"
    elsif policy.cancelled?
      "Cancelled"
    else
      "Valid from " + policy.start_date.to_s(:rfc822) + " to " + policy.end_date.to_s(:rfc822)
    end
  end
end

app/views/policies/_no_policies.html.erb
<!-- This is pretty much a duplicate of the no_clients screen
     TODO perhaps consolidate into one partial and feed that relavant variables
     via helper -->
<div class="ui center aligned container">
  <%= image_tag("thinking-clipart.svg", class: "ui centered medium image") %>
  <div class="ui small header">
    looks like there aren't any policies yet, <%= link_to 'add a new policy', new_policy_path %>
  </div>
</div>

app/views/policies/_policy.html.erb
<div class="ui centered raised teal card">
  <div class="content">
    <%= link_to edit_policy_path @policy do %>
      <div class="ui teal circular basic icon button right floated" data-tooltip="Edit policy info" data-inverted="">
        <i class="write icon"></i>
      </div>
    <% end %>
    <div class="header">
      <%= @policy.number %>
    </div>
    <div class="meta">
      <span><%= @policy.policy_type.capitalize + " policy " if @policy.policy_type %></span>
    </div>
  </div>

  <div class="content">
    <div class="ui relaxed list">
      <div class="item">
        <i class="car middle aligned icon"></i>
        <div class="content">
          <% if @policy.vehicle %>
            <%= link_to @policy.vehicle.registration_no, @policy.vehicle, class: 'header' %>
            <%= link_to @policy.vehicle, class:'description' do %>
              <em><%= @policy.vehicle.year_of_manufacture %> <%= @policy.vehicle.make %> <%= @policy.vehicle.model %></em>
            <% end %>
          <% else %>
            <h4>No vehicle</h4>
          <% end %>
        </div>
      </div>
      <div class="item">
        <i class="user middle aligned icon"></i>
        <div class="content">
          Client is <%= link_to "#{@policy.client.other_names || ""} #{@policy.client.lastname}", @policy.client %>
        </div>
      </div>
      <div class="item">
        <i class="building outline middle aligned icon"></i>
        <div class="content">
          Insured by <b><%= @policy.insurer ? link_to(@policy.insurer.name.upcase, @policy.insurer) : '--unavailable--' %></b>
        </div>
      </div>
      <div class="item">
        <i class="calendar middle aligned icon"></i>
        <div class="content">
          Valid from <b><%= @policy.start_date.to_s :rfc822 %></b></br> to <b><%= @policy.end_date.to_s :rfc822 %></b> <!-- make this red if expired -->
        </div>
      </div>
      <div class="item">
        <i class="money middle aligned icon"></i>
        <div class="content">
          <a class="header"><%= number_to_currency((@policy.commission/100)  * @policy.premium) %> commission</a>
          <div class="description">
            <em><%= @policy.commission %>% of <%= number_to_currency(@policy.premium) %> premium</em>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="extra content">
    <span class="right floated">
      <h5 class="ui <%= @policy.issued? ? 'green' : 'red' %> header">
        <%= @policy.issued? ? "Issued #{@policy.issue_date.to_s :rfc822}" : @policy.status.humanize %>
      </h5>
    </span>
    <span>
      <% if @policy.expired? %>
        <h5 class="ui red header">EXPIRED</h5>
      <% end %>
    </span>
  </div>
</div>

app/views/policies/_policy_form.html.erb
<!-- form -->
<%= form_for(policy, html: { class: 'ui form' }) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="field <%= "error" if policy.errors.details.key? :insurer %>">
    <%= f.label :insurer %>
    <%= f.collection_select :insurer_id, current_user.insurers.all, :id, :name_in_caps, {prompt: "Select the insurance company"}, {class: "ui search dropdown"} %>
    <%= render_error_label policy, :insurer %>
  </div>

  <div class="field <%= "error" if policy.errors.details.key? :number %>">
    <%= f.label :number, 'Policy number' %>
    <%= f.text_field :number, autofocus: true %>
    <%= render_error_label policy, :number %>
  </div>

  <div class="field <%= "error" if policy.errors.details.key? :policy_type %>">
    <%= f.label :policy_type %>
    <%= f.text_field :policy_type, autofocus: true %>
    <%= render_error_label policy, :policy_type %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <div class="three fields">
      <!-- TODO Sort out error rendering for wrapping field div which is added by jquery in policies.coffee -->
      <%= f.date_select :start_date, { prompt:{ day:'Start day', month:'Start month', year:'Start year' } }, { class:"ui dropdown compact for_date #{"error" if policy.errors.details.key? :start_date}" } %>
      <%= render_error_label policy, :start_date, '' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <div class="three fields">
      <!-- TODO Sort out error rendering for wrapping field div which is added by jquery in policies.coffee -->
      <%= f.date_select :end_date, { prompt:{ day:'End day', month:'End month', year:'End year' } }, { class:"ui dropdown compact for_date #{"error" if policy.errors.details.key? :end_date}" } %>
      <%= render_error_label policy, :end_date, '' %>
    </div>
  </div>

  <div class="three fields">
    <div class="field <%= "error" if policy.errors.details.key? :premium %>">
      <%= f.label :premium, 'Premium (GHS)' %>
      <%= f.number_field :premium, step: 0.01, autofocus: true %>
      <%= render_error_label policy, :premium %>
    </div>
    <div class="field <%= "error" if policy.errors.details.key? :commission %>">
      <%= f.label :commission, 'Commission (%)' %>
      <%= f.number_field :commission, step: 0.001, autofocus: true %>
      <%= render_error_label policy, :commission %>
    </div>
    <div class="field <%= "error" if policy.errors.details.key? :discount %>">
      <%= f.label :discount, 'Discount (%)' %>
      <%= f.number_field :discount, step: 0.001, autofocus: true %>
      <%= render_error_label policy, :discount %>
    </div>
  </div>

  <div class="field <%= "error" if policy.errors.details.key? :client %>">
    <%= f.label :client %>
    <%= f.collection_select :client_id, current_user.clients.all, :id, :lastname_other_names, {prompt: "Select the vehicle owner"}, {class: "ui search dropdown"} %>
    <%= render_error_label policy, :client %>
  </div>

  <div class="field <%= "error" if policy.errors.details.key? :vehicle %>">
    <%= f.label :vehicle %>
    <%= f.collection_select :vehicle_id, current_user.vehicles.all, :id, :reg_make_model, {prompt: "Select the vehicle"}, {class: "ui search dropdown"} %>
    <%= render_error_label policy, :vehicle %>
  </div>

  <div class="ui segment">
    <div class="ui teal ribbon label">
      <i class="info circle icon"></i>
      Validation
    </div>
    <div class="ui list">
      <div class="item">
        Date on which policy is issued. Commission revenue is calculated for this date.
      </div>
      <div class="item">
        Default is today.
      </div>
    </div>
    <div class="three fields">
      <!-- TODO Sort out error rendering for wrapping field div which is added by jquery in policies.coffee -->
      <%= f.date_select :issue_date, { default: Date.today }, { class:"ui dropdown compact for_date #{"error" if policy.errors.details.key? :issue_date}" } %>
      <%= render_error_label policy, :issue_date, '' %>
    </div>
    <div class="ui list">
      <div class="item">
        Please select the policy status
      </div>
    </div>
    <div id="status_selection" class="two fields">
      <!--  TODO checkboxes from which user can select one of issue, cancelled or expired.
            Expired is disabled by default and the remaining options are also disabled on policy expiration -->
      <div class="field">
        <div class="ui toggle checkbox">
          <%= f.radio_button(:status, "issued")  %>
          <%= f.label(:status, "ISSUED") %>
        </div>
      </div>
      <div class="field">
        <div class="ui toggle checkbox">
          <%= f.radio_button(:status, "cancelled")  %>
          <%= f.label(:status, "CANCELLED") %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <div class="two ui buttons">
      <%= link_to 'Cancel', (request.referer.present? ? request.referer : authenticated_root_path), class:'ui button' %>
      <div class="or"></div>
      <%= f.submit action, class: "ui positive button" %>
    </div>
  </div>

<% end %>

app/views/policies/_policy_table.html.erb
<table class="ui unstackable selectable teal table">
  <thead>
    <tr>
      <th>Policy No.</th>
      <th>Asset</th>
      <th>Insurer</th>
      <th>Status</th>
    </tr>
  </thead>

  <% policies.each do |policy| %>
    <tr>
      <td class="selectable" data-tooltip="<%= policy_cell_pop_up policy %>" data-position="right center">
        <%= policy.number ? (link_to policy.number, policy) : (link_to "Policy number not given", policy) %>
      </td>
      <td class="selectable">
        <!--IDEA icon dependant on asset type, will have to remove cell's selectable class though -->
        <%= link_to "#{policy.vehicle ? policy.vehicle.registration_no : "--"}", '#' %>
      </td>
      <td class="selectable"><%= policy.insurer ? link_to(policy.insurer.name.upcase, policy.insurer) : '--unavailable--' %></td>
      <td class="selectable <%= policy_table_cell_class policy %>" data-tooltip="<%= policy_cell_pop_up policy %>" data-position="left center">
        <%= link_to (policy.status.humanize + " #{'(expired)' if policy.expired?}"), policy %>
      </td>
    </tr>
  <% end %>
</table>

app/views/policies/edit.html.erb
<div class="ui grid container">

  <div class="row">
      <div class="sixteen wide mobile eight wide tablet eight wide computer column">

        <div class="ui header">
          <i class="file text icon"></i>
          <div class="content">
            Edit Policy
            <div class="sub header">
              Edit Policy information
            </div>
          </div>
        </div>

        <div class="ui clearing divider"></div>

        <% if @policy.expired? %>
          <div class="ui warning icon message">
            <i class="icons">
              <i class="huge red dont icon"></i>
              <i class="big black file text icon"></i>
            </i>
            <div class="content">
              <div class="header">
                EXPIRED
              </div>
              <p>Policy's end date has passed</p>
            </div>
          </div>
        <% end %>

        <%= render 'policy_form', policy: @policy, action: 'Save changes' %>

        <div class="ui divider"></div>

        <div class="ui inverted clearing segment">
          <h5 class="ui red inverted header">
            Delete policy
            <div class="sub header">
              This action permanently removes this policy from the database.
              You will lose all related policy data
            </div>
          </h5>
          <%= link_to @policy, method: :delete, data: {confirm: "Are you sure you want to delete this policy?"}, class:'ui inverted right floated red basic button' do %>
            <i class="icon trash"></i>
            Delete this policy
          <% end %>
        </div>

      </div>
  </div>

</div>

app/views/policies/index.html.erb
<div class="ui container">
  <!-- page header -->
  <%= link_to new_policy_path do %>
    <div class="ui teal circular basic icon large button right floated" data-tooltip="add new policy" data-inverted="" data-position="bottom center">
      <i class="plus icon"></i>
    </div>
  <% end %>

  <h1 class="ui left floated header">
    <i class="folder open icon"></i>
    <div class="content">
      Policies
      <div class="sub header">
        View all policies
      </div>
    </div>
  </h1>

  <!-- client list -->
  <!-- TODO clean this up!! -->
  <%= @policies.any? ? (render partial: 'policy_table', locals: { policies: @policies }) : (render 'no_policies') %>
</div>

app/views/policies/new.html.erb
<div class="ui grid container">

  <div class="row">
      <div class="sixteen wide mobile eight wide tablet eight wide computer column">

        <div class="ui header">
          <i class="big icons">
            <i class="file text icon"></i>
            <i class="corner add icon"></i>
          </i>
          <div class="content">
            Add Policy
            <div class="sub header">
              Add a new policy to your portfolio
            </div>
          </div>
        </div>

        <div class="ui clearing divider"></div>

        <%= render 'policy_form', policy: @policy, action: 'Add Policy' %>

      </div>
  </div>

</div>

app/views/policies/show.html.erb
<div class="ui internally celled stackable grid container">
  <div class="row">
    <div class="five wide column">
      <!-- policy card -->
      <%= render @policy %>

      <!-- go back to policy list -->
      <%= link_to policies_path, class:'ui animated fade fluid teal basic button' do %>
        <div class="visible content">
          <i class="open folder icon"></i>
          policies
        </div>
        <div class="hidden content">
          go to Policy list
        </div>
      <% end %>
    </div>

    <div class="eleven wide column">

      <!-- policy number header -->
      <h2 class="ui left floated header">
        Policy: <%= @policy.number ? @policy.number : "Policy number not yet issued" %>
      </h2>
      <!-- policy action button header TODO add button for when policy is expired that links to policy dates part of policy form  -->
      <% if @policy.not_issued? %>
        <%= link_to "Issue policy", edit_policy_path(@policy, anchor: "status_selection"), data: { confirm: "This will take you to the Validation section of this policy's settings. Proceed?" }, class: "ui positive right floated button" %>
      <% elsif @policy.issued? %>
        <%= link_to "Cancel policy", edit_policy_path(@policy, anchor: "status_selection"), data: { confirm: "This will take you to the Validation section of this policy's settings. Proceed?" }, class: "ui basic negative right floated button" %>
      <% elsif @policy.cancelled? %>
        <%= link_to "Re-Issue policy", edit_policy_path(@policy, anchor: "status_selection"), data: { confirm: "This will take you to the Validation section of this policy's settings. Proceed?" }, class: "ui positive right floated button" %>
      <% end %>

      <div class="ui clearing divider"></div>

      <!-- if policy has assets -->

      <!-- if policy has claims -->

    </div>
  </div>
</div>